config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :athlets do
    collection do
      get :autocomplete_firstname
      get :autocomplete_surname
      get :autocomplete_club
      post :import
      get :suggestions
      delete :destroy_all

      get :show_multiple
      get :new_multiple
      get :edit_multiple
      post :create_multiple
      put :update_multiple
      put :destroy_multiple
    end
  end

  resources :relays do
    collection do
      delete :destroy_all
    end
  end

  root 'static_pages#home'

  
  get 'datatable_i18n', to: 'datatables#datatable_i18n'
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

end

app/views/static_pages/home.html.erb
<!--<div class="jumbotron" style="margin-bottom: 100px;">
  <div class="media">
    <a class="pull-left" href="#">
      <%= image_tag('web_hi_res_512.png', height: '124') %>
    </a>
    <div class="media-body">
      <h1 class="media-heading" style="text-align: right">TGT & SV 1911 TRAISA</h1>
      <h2 class="media-heading" style="text-align: right">Veranstaltungsjahr 2016</h2>
    </div>
  </div>
</div>-->

<!-- <div class="row">
  <div class="col-lg-12">
    <h2>Wettbewerbe</h2>
  </div>
</div> -->

<div class="page-header">
  <h1 id="navbar" class="media-heading" style="text-align: right">TGT & SV 1911 TRAISA</h1>
  <h2 class="media-heading" style="text-align: right">Wettbewerbe 2019</h2>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Einzelstarter</h3>
      </div>
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
        <% Event.where(:team_size => 1).where(:active => true).each do |event| %>
          <li>
            <%= link_to athlets_path(:eventname => event.name) do %>
              <%= event.name %>
              <span class="badge badge-info pull-right">
                <%= Athlet.where(:eventname => event.name).distinct.count %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul><br />
      <%= link_to destroy_all_athlets_path, :class => 'btn btn-info pull-right', method: :delete do %>
        <%= fa_icon 'trash-o' %>
        Alle Einzelläufer löschen
      <% end if false %>
    </div>
  </div>
</div>
<div class="col-md-4">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Staffeln</h3>
    </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <% Event.where.not(:team_size => 1).where(:active => true).each do |event| %>
          <li>
            <%= link_to relays_path(:eventname => event.name) do %>
              <%= event.name %>
              <span class="badge badge-success pull-right">
                <%= Athlet.where(:eventname => event.name).distinct.count(:relaystarter) %>
              </span>
            <% end %>
          </li>
        <% end %>
      </ul><br />
      <%= link_to destroy_all_relays_path, :class => 'btn btn-success pull-right', method: :delete do %>
        <%= fa_icon 'trash-o' %>
        Alle Staffeln löschen
      <% end if false %>
    </div>
  </div>
</div>

<div class="col-md-4">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Export</h3>
    </div>
    <div class="panel-body">
      <ul class="nav nav-pills nav-stacked">
        <li>
          <%= link_to athlets_path(format: "csv") do %>
          <%= fa_icon 'download' %> CSV
          <% end %>
        </li>
        <li>
          <%= link_to athlets_path(format: "xls") do %>
          <%= fa_icon 'download' %> Excel
          <% end %>
        </li>
      </ul>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Import</h3>
    </div>
    <div class="panel-body">
      <%= form_tag import_athlets_path, multipart: true do %>
      <!-- <span class="btn btn-primary btn-file">
        Durchsuchen <%= file_field_tag :file %>
      </span> -->
      <div class="input-group">
        <span class="input-group-btn">
          <span class="btn btn-default btn-file">
            <%= fa_icon 'search' %>
            Durchsuchen <%= file_field_tag :file %>
          </span>
        </span>
        <input type="text" class="form-control" readonly="">
      </div>
      <br />
      <button type="submit" class="btn btn-primary pull-right">
        <%= fa_icon 'upload' %>
        Upload
      </button>
      <% end %>
    </div>
  </div>
</div>
</div>