config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :athlets do
    collection do
      get :autocomplete_firstname
      get :autocomplete_surname
      get :autocomplete_club
      post :import
      get :suggestions
      delete :destroy_all

      get :show_multiple
      get :new_multiple
      get :edit_multiple
      post :create_multiple
      put :update_multiple
      put :destroy_multiple
    end
  end

  resources :relays do
    collection do
      delete :destroy_all
    end
  end

  root 'static_pages#home'

  
  get 'datatable_i18n', to: 'datatables#datatable_i18n'
 
end

app/models/relay.rb
class Relay < Tableless
  #has_no_table
  has_many :athlets, :primary_key => :relaystarter, :foreign_key => :relaystarter, :class_name => RelayMember
  accepts_nested_attributes_for :athlets

  #attr_accessor :id
  attr_accessor :new_record

  column :club, :string
  column :eventname, :string
  column :relaystarter, :integer
  column :relaytmsize, :integer
  column :relaystarttime, :string


  validates :club, :presence => true, length: { minimum: 1 }
  validates :eventname, :presence => true
  validates :relaystarter, :presence => true

  after_initialize :set_defaults
  after_initialize :build_athlets

  #attr_accessible :club, :eventname, :relaystarter, :relaytm, :athlets_attributes
  #def id
  #  @id ||= 1
  #end
  
  def self.allowed_attributes
    ['club', 'eventname', 'relaystarter', 'relaytmsize']
  end

  def self.find(id)
    athlets = Athlet.where(:relaystarter => id)

    if athlets
      puts athlets.first.attributes
      Relay.new(athlets.first.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false}))
    else
      nil
    end
  end


  def self.all
    athlets = Athlet.where.not(:relaytmsize => 1).group(:relaystarter).all
    athlets.map{ |athlet| Relay.new(athlet.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false})) }
  end

  def self.event(name)
    athlets = Athlet.where(:eventname => name).group(:relaystarter).all
    #merged = athlet.attributes.slice(Relay.allowed_attributes).merge({:new_record => false})
    #athlets.map{ |athlet| Relay.new(merged) }
    athlets.map do |athlet|
      merged = athlet.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false})
      Relay.new(merged)
    end
  end

  def to_param
    self.relaystarter
  end

  def set_defaults
    #self.relaytmsize ||= self.event.team_size
    self.relaytmsize ||= 4
  end

  def build_athlets
    (relaytmsize - athlets.size).times do
      self.athlets.build
    end if self.new_record?
  end

  def save
    if valid?
      # Maybe capture this in a transaction
      index = 1
      self.athlets.map do |athlet|
        athlet.assign_attributes(self.attributes.slice(*Relay.allowed_attributes))
        athlet.starter = (athlet.relaystarter * 10) + index
        athlet.relaytm = index
        if athlet.transponderid.blank?
          athlet.transponderid = athlet.starter;
        end
        if athlet.starttime.blank?
          if !self.relaystarttime.blank?
              athlet.starttime = self.relaystarttime
          end
        end
        athlet.save
        index = index + 1
      end
    end
  end

  def destroy
    self.athlets.map(&:destroy)
  end

  # def update(params)
  #   params
  #   debugger
  # end
end

app/controllers/athlets_controller.rb
class AthletsController < ApplicationController
  before_action :set_athlet, only: [:show, :edit, :update, :destroy]

  include ActionView::Helpers::TextHelper

  # Autocompletion
  def autocomplete_firstname
    render :json => Athlet.where('firstname LIKE ?', "%#{params[:term]}%").limit(15).order(:firstname).pluck(:firstname).uniq
  end

  def autocomplete_surname
    render :json => Athlet.where('surname LIKE ?', "%#{params[:term]}%").limit(15).order(:surname).pluck(:surname).uniq
  end

  def autocomplete_club
    render :json => Athlet.where('club LIKE ?', "%#{params[:term]}%").limit(15).order(:club).pluck(:club).uniq
  end


  # Actions
  def import
    Athlet.import(params[:file])
    redirect_to(root_url, notice: "Athlets imported")
  end


  def index
    if params[:eventname]
      session[:eventname] = params[:eventname]
    end
    # if params[:eventname]
    #   #p params[:eventname]
    #   debugger
    #   @athlets = Athlet.order(:eventname).order(:starter).where(:eventname => params[:eventname])
    # else
      if params[:transponderid]
        #p params[:transponderid]
        #@athlets = Athlet.order(:event).order(:starter).where(:transponderid => params[:transponderid]).all
        @athlets = Athlet.joins(:event).where(events: {active: true}).order(:eventname).order(:starter).where(:transponderid => params[:transponderid]).all
      else
        @athlets = Athlet.order(:eventname).order(:starter).all
      end
    #end

    #@athlets = Athlet.where(:relaytmsize => 1).all
    #@relays = Athlet.where.not(:relaytmsize => 1).group(:relaystarter)

    respond_to do |format|
      format.html
      format.csv { send_data @athlets.to_csv }
      #format.xls { send_data @athlets.to_xls }

      # gem 'to_xls-rails'
      format.xls {
        #response.headers["Content-Disposition"] = 'attachement; filename='+Time.now.strftime("%Y%m%dT%H%M%S")+'.txt'
        send_data @athlets.to_xls(
                      #:except => [:created_at, :updated_at]
                      :only => Athlet::allowed_attributes.map { |x| x.to_sym },
                      :header => true,
                      :header_columns => Athlet::allowed_attributes_xls,
                      #:prepend => [["Col 0, Row 0", "Col 1, Row 0"], ["Col 0, Row 1"]]
                  ), :filename => 'athlets_' + Time.now.strftime("%Y%m%dT%H%M%S")+'.xls' }

      format.json
      #format.json { render json: @athlets }
      #format.json { render json: @athlets.to_json(:except => :event) }
      format.xml { render xml: @athlets }
    end
  end


  def show
    respond_to do |format|
      format.html
      format.json { render json: @athlet }
      format.xml { render xml: @athlet }
    end
  end

  def suggestions
    #@athlets = Athlet.select("athlets.*, GROUP_CONCAT(athlets.eventname SEPARATOR ', ') AS events")
    # sqlite variante
    @athlets = Athlet.select("athlets.*, GROUP_CONCAT(athlets.eventname, ', ') AS events")
    @athlets = @athlets.group("firstname, surname, sex, birthday").limit(5)
    @athlets = @athlets.where("firstname LIKE (?)", "%#{params[:firstname]}%") if params[:firstname].present?
    @athlets = @athlets.where("surname LIKE (?)", "%#{params[:surname]}%") if params[:surname].present?
    # TODO: year and sex
  end


  def show_multiple
    @athlets = Athlet.where(:relaystarter => params[:relaystarter])
  end


  def new
    @athlet = Athlet.new(:eventname => params[:eventname])
    @athlet.relaytmsize = 1
    session[:eventname] = @athlet.eventname
    #session[:eventname] = params[:eventname]
  end


  def new_multiple
    @athlets = [];
    3.times { @athlets << Athlet.new({:relaytmsize => 3}) }
    render :form_multiple
  end


  def edit
    session[:eventname] = @athlet.eventname
    #params[:eventname]
  end


  def edit_multiple
    @athlets = Athlet.where(:relaystarter => params[:relaystarter])
    render :form_multiple
  end


  def create
    @athlet = Athlet.new(athlet_params)
    @athlet.relaytmsize = 1
    if @athlet.transponderid.blank?
      @athlet.transponderid = @athlet.starter;
    end
    if @athlet.save
      session[:eventname] = @athlet.eventname
      #https://github.com/rails-api/rails-api/blob/master/lib/rails-api/templates/rails/scaffold_controller/controller.rb
      respond_to do |format|
        format.html { redirect_to @athlet, notice: 'Athlet was successfully created.' }
        format.json { render json: @athlet, status: :created, location: @athlet }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @athlet.errors, status: :unprocessable_entity }
      end
    end

  end


  def create_multiple
    athlets_attributes = params[:athlets] # make a temporary copy
    @athlets = []
    athlets_attributes.each do |value|
      value[:starter] = params[:athlet][:starter]
      value[:relaystarter] = params[:athlet][:relaystarter]
      value[:eventname] = params[:athlet][:eventname]
      value[:club] = params[:athlet][:club]

      @athlets << Athlet.new(check_permission(value))
    end

    begin
      Athlet.transaction do
        success = @athlets.map(&:save!)
      end
    rescue ActiveRecord::RecordInvalid => invalid
      render :form_multiple
      return
    end
    redirect_to athlets_url, notice: 'Relay was successfully updated.'
    #http://ramblingabout.wordpress.com/2009/05/23/saving-different-active-record-classes-in-a-single-transaction/
    #http://stackoverflow.com/questions/2567133/work-with-rescue-in-rails
    #http://stackoverflow.com/questions/6326451/rails-3-transactions-rolling-back-everything
    #http://stackoverflow.com/questions/2246036/rails-transaction-doesnt-rollback-on-validation-error
    #http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html
  end


  def update

    if params[:athlet][:transponderid].blank?
      params[:athlet][:transponderid] = params[:athlet][:starter]
    end
    if @athlet.update(athlet_params)
      session[:eventname] = @athlet.eventname
      #https://github.com/rails-api/rails-api/blob/master/lib/rails-api/templates/rails/scaffold_controller/controller.rb
      respond_to do |format|
        format.html { redirect_to @athlet, notice: 'Athlet was successfully updated.' }
        #format.json { head :no_content }
        format.json { render json: @athlet, status: :created, location: @athlet }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: @athlet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_multiple
    athlets_attributes = params[:athlets] # make a temporary copy
    athlets_attributes.each do |key, value|
      #athlets_attributes.each do |value|
      value[:starter] = params[:athlet][:starter]
      value[:eventname] = params[:athlet][:eventname]
      value[:club] = params[:athlet][:club]
    end
    @athlets = Athlet.update(athlets_attributes.keys, athlets_attributes.values)
    @athlets.reject! { |p| p.errors.empty? }
    if @athlets.empty?
      redirect_to athlets_url, notice: 'Relay was successfully updated.'
    else
      render :form_multiple
    end
  end


  def destroy
    @athlet.destroy

    #https://github.com/rails-api/rails-api/blob/master/lib/rails-api/templates/rails/scaffold_controller/controller.rb
    respond_to do |format|
      format.html { redirect_to athlets_url, notice: 'Athlet was successfully destroyed.' }
      #format.json { head :no_content }
      format.json { head :no_content, status: :success }
    end
  end


  def destroy_multiple
    @athlets = Athlet.where(:relaystarter => params[:relaystarter])
    @athlets.destroy_all
    redirect_to athlets_url, notice: 'Relay was successfully destroyed.'
  end


  def destroy_all
    @athlets = Athlet.where(:relaytmsize => 1)
    @athlets.destroy_all
    redirect_to root_url, notice: 'Athlets were successfully destroyed.'
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_athlet
    @athlet = Athlet.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def athlet_params
    params.require(:athlet).permit(:starter, :firstname, :surname, :birthday, :sex, :club, :eventname, :relaytm, :relaystarter, :relaytmsize, :transponderid, :starttime, :additionals)
  end

  def check_permission(attributes)
    attributes.permit(:starter, :firstname, :surname, :birthday, :sex, :club, :eventname, :relaytm, :relaystarter, :relaytmsize, :transponderid, :starttime, :additionals)
  end
end

app/helpers/athlets_helper.rb
module AthletsHelper
end

app/views/athlets/_athlet_suggestion.html.erb
<div class="athlet_suggestion">
  <div class="name"><%= athlet.name %></div>
  <div class="birthday"><%= athlet.birthday %></div>
  <div class="sex"><%= athlet.sex %></div>
  <div class="club"><%= athlet.club %></div>
</div>

app/views/athlets/_form.html.erb
<div class="row">
  <div class="col-xs-8">
    <div class="panel panel-primary athlet">
      <div class="panel-heading">Athlet</div>
      <div class="panel-body">
        <%= simple_form_for(@athlet, html: { class: 'form-horizontal' },
          wrapper: :horizontal_form,
          wrapper_mappings: {
            check_boxes: :horizontal_radio_and_checkboxes,
            radio_buttons: :horizontal_radio_and_checkboxes,
            file: :horizontal_file_input,
            boolean: :horizontal_boolean
          }) do |f| %>
          <%= f.error_notification %>
            <% @athlet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>

          <div class="form-inputs">
            <%= f.input :starter %>

            <%= f.input :surname, :input_html => { :class => :surname,
              :data => { :autocomplete => autocomplete_surname_athlets_path } } %>
            <%= f.input :firstname, :input_html => { :class => :firstname,
              :data => { :autocomplete => autocomplete_firstname_athlets_path } } %>
            <%#= f.input :birthday, :as => :integer, :input_html => { :class => :birthday, :value => @athlet.birthday } %>
            <%= f.input :birthday, :as => :string, :input_html => { :class => :birthday, :value => @athlet.birthday } %>
            <%# http://stackoverflow.com/questions/10767859/overriding-model-attribute-readers-does-not-affect-simple-form-input-fields %>
            <%#= f.input :sex %>

            <%= f.input :sex, collection: [:M, :W, :U], :input_html => { :class => :sex }  %>

            <%= f.input :club, :input_html => { :class => :club,
              :data => { :autocomplete => autocomplete_club_athlets_path } } %>
            <%#= f.input :event %>
            <%= f.input :eventname,
            :as => :select,
            :collection => Event.where(:team_size => 1).where(:active => true).order(:name => :asc),
            :label_method => :name,
            :value_method => :name,
            :include_blank => false,
            :input_html => { :class => "chosen"} %>
            <%#= f.input :event, :as => :hidden %>
            <%#= f.input :relaytm %>
            <%#= f.input :relaystarter %>
            <%= f.input :relaytmsize, :as => :hidden %>
            <%= f.input :transponderid %>
            <%= f.input :starttime %>
            <%= f.input :additionals %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, :class => "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div id="suggestionBar" class="affix-top" data-spy="affix" data-offset-top="160" data-offset-bottom="0">
      <div class="panel panel-primary athlet">
        <div class="panel-heading">
          <%= fa_icon 'refresh' %>
          Vorschläge
        </div>
      </div>
      <div id="suggestionBox"></div>
    </div>
  </div>
</div>

app/views/athlets/edit.html.erb
<h1>Athlet bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Details', @athlet, :class => 'btn btn-default' %>
<%= link_to 'Übersicht', athlets_path, :class => 'btn btn-default' %>

app/views/athlets/edit_multiple.html.erb
<h1>Edit Relay</h1>

<%= form_tag update_multiple_athlets_path, method: :put, class: 'form-horizontal' do %>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">Relay</div>
        <div class="panel-body">
          <%= simple_fields_for @athlets.first, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
            <div class="row">
              <div class="col-md-6">
            <%= f.input :starter %>
            <%= f.input :club, :input_html => {
              :data => { :autocomplete => autocomplete_club_athlets_path } } %>
        </div>
              <div class="col-md-6">
            <%= f.input :event %>
          </div>
        </div>
          <% end %>
        </div>
      </div>
    </div>
    <% @athlets.each do |athlet| %>

      <% if false %><!-- Errors -->
        <li>
          <%= hidden_field_tag "athlet_ids[]", athlet.id %>
          <%= athlet.surname %>
          <ul class="errors">
            <% athlet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </li>
      <% end %>


      <div class="col-md-6">
        <div class="panel panel-info">
          <div class="panel-heading">Athlet</div>
          <div class="panel-body">
            <%= simple_fields_for "athlets[]", athlet, wrapper: :horizontal_form do |f| %>
              <% if athlet.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(athlet.errors.count, "error") %> prohibited this athlet from being saved:</h2>
                  <ul>
                  <% athlet.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <%= f.input :firstname, :input_html => {
                :data => { :autocomplete => autocomplete_firstname_athlets_path } } %>
              <%= f.input :surname, :input_html => {
                :data => { :autocomplete => autocomplete_surname_athlets_path } } %>
              <%= f.input :birthday, :as => :integer, :input_html => { :value => athlet.birthday } %>
              <%# http://stackoverflow.com/questions/10767859/overriding-model-attribute-readers-does-not-affect-simple-form-input-fields %>
              <%#= f.input :sex %>

              <%= f.input :sex, collection: [:M, :F] %>

              <%= f.input :relaytmsize, :as => :hidden %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= submit_tag "Update" %>
  </div>
<% end %>

app/views/athlets/form_multiple.html.erb
<!-- <h3>Edit Relay</h3> -->
<div class="page-header">
  <h1 id="navbar">Staffel bearbeiten</h1>
</div>

<div class="row">
  <div class="col-xs-8">

<% new_record = @athlets.first.new_record? %>
<%= form_tag new_record ? create_multiple_athlets_path : update_multiple_athlets_path,
  method: new_record ? :post : :put, class: 'form-horizontal' do %>
  <div class="row relay">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= fa_icon "users" %>
          Relay
        </div>
        <div class="panel-body">
          <%= simple_fields_for @athlets.first, html: { class: 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
            <div class="row">
              <div class="col-md-6">
                <div class="virtual-panel-left">
                  <%= f.input :relaystarter %>
                  <%= f.input :starter %>
                  <%= f.input :club, :input_html => {
                    :data => { :autocomplete => autocomplete_club_athlets_path } } %>
                </div>
              </div>
              <div class="col-md-6">
                <div class="virtual-panel-right">
                  <%= f.input :eventname %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% count = 0 %>
    <% @athlets.each do |athlet| %>

      <% if false %><!-- Errors -->
        <li>
          <%= hidden_field_tag "athlet_ids[]", athlet.id %>
          <%= athlet.surname %>
          <ul class="errors">
            <% athlet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </li>
      <% end %>


      <div class="col-md-6">
        <div class="panel panel-info athlet">
          <!-- <div class="panel-heading">Athlet</div> -->
          <div class="panel-body">
            <%= simple_fields_for "athlets[]", athlet, wrapper: :horizontal_form do |f| %>
              <fieldset>
                <legend>
                  <%#= fa_icon "users" %>
                  Athlet <%= (count += 1) %>
                </legend>
                <% if athlet.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(athlet.errors.count, "error") %> prohibited this athlet from being saved:</h2>
                    <ul>
                    <% athlet.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                <%= f.input :firstname, :input_html => {
                  :class => :firstname, :data => { :autocomplete => autocomplete_firstname_athlets_path } } %>
                <%= f.input :surname, :input_html => {
                  :class => :surname, :data => { :autocomplete => autocomplete_surname_athlets_path } } %>
                <%#= f.input :birthday, :as => :integer, :input_html => { :class => :birthday, :value => athlet.birthday } %>
                <%= f.input :birthday, :as => :string, :input_html => { :class => :birthday, :value => athlet.birthday } %>
                <%# http://stackoverflow.com/questions/10767859/overriding-model-attribute-readers-does-not-affect-simple-form-input-fields %>
                <%#= f.input :sex %>

                <%= f.input :sex, collection: [:M, :W, :U], :input_html => { :class => :sex } %>

                <%= f.input :relaytmsize, :input_html => { :class => :relaytmsize }, :as => :hidden %>
                <%= f.input :transponderid, :input_html => { :class => :transponderid, :value => athlet.transponderid } %>
                <%= f.input :starttime, :input_html => { :class => :starttime, :value => athlet.starttime } %>
                <%= f.input :additionals, :input_html => { :class => :additionals, :value => athlet.additionals } %>
              </fieldset>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="actions">
    <%= submit_tag "Aktualisieren", :class => "btn btn-primary" %>
  </div>
<% end %>

  </div>
  <div class="col-xs-4">
    <div id="suggestionBar" class="affix-top" data-spy="affix" data-offset-top="160" data-offset-bottom="0">
      <div class="panel panel-primary athlet">
        <div class="panel-heading">
          <%= fa_icon 'refresh' %>
          Vorschläge
        </div>
      </div>
      <div id="suggestionBox"></div>
    </div>
  </div>
</div>

app/views/athlets/index.html.erb
<div class="page-header">
  <h1>Einzelstarter</h1>
</div>

<ul class="nav nav-tabs" role="tablist">
  <% events = Event.where(:team_size => 1).where(:active => true) %>
  <%# debugger %>
  <% session[:eventname] = Event.first.name if session[:eventname].nil? %>
  <% events.each do |event| %>
    <%# debugger %>
      <li class="<%= (event.name == session[:eventname]) ? 'active' : '' %>">
        <a href="#<%= event.name %>" role="tab" data-toggle="tab"><%= event.name %></a></li>
  <% end %>
</ul>

<div class="tab-content">
  <% active = true %>
  <% Event.where(:team_size => 1).where(:active => true).each do |event| %>
      <div class="tab-pane <%= (event.name == session[:eventname]) ? 'active' : '' %>" id="<%= event.name %>">
        <% active = false %>
        <!-- <div class="section"> -->
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title">
              <%= event.name %>
            </div>
          </div>
        </div>
        <%= link_to 'Neuer Athlet', new_athlet_path(:eventname => event.name), :class => 'btn btn-primary' %>
        <br />
        <br />
        <table class="table table-bordered table-striped datatable searchable">
          <thead>
          <tr>
            <th>Starter</th>
            <th>Name</th>
            <th>Geburtsjahr</th>
            <th>Geschlecht</th>
            <th>Verein</th>
            <th>Veranstaltung</th>
            <th>Staffel Teilnehmer</th>
            <th>Staffel-Startnummer</th>
            <th>Transp.-Id</th>
            <th>Startzeit</th>
            <th>Additionals</th>
            <th class="no-sort"></th>
          </tr>
          </thead>

          <tbody>
          <% @athlets.where(:eventname => event.name).each do |athlet| %>
              <tr>
                <td><%= athlet.starter %></td>
                <td><%= link_to athlet.name, athlet %></td>
                <td><%= athlet.birthday %></td>
                <td><%= athlet.sex %></td>
                <td><%= athlet.club %></td>
                <td><%= athlet.eventname %></td>
                <td><%= athlet.relaytm %></td>
                <td><%= athlet.relaystarter %></td>
                <td><%= athlet.transponderid %></td>
                <td><%= athlet.starttime %></td>
                <td><%= athlet.additionals %></td>
                <td>
                  <%= link_to edit_athlet_path(athlet), :title => t("general.edit"), :data => {:toggle => "tooltip"} do %>
                      <%= tag :span, :class => "glyphicon glyphicon-edit" %>
                  <% end %>
                  <%= link_to athlet, :title => t("general.destroy"), data: {confirm: t('general.are_you_sure'), :toggle => "tooltip"}, method: :delete do %>
                      <%= tag :span, :class => "glyphicon glyphicon-trash" %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>

        <%= link_to 'Neuer Athlet', new_athlet_path(:eventname => event.name), :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/athlets/new.html.erb
<h1>Neuen Athleten anmelden</h1>

<%= render 'form' %>

<%= link_to 'Übersicht', athlets_path, :class => 'btn btn-default' %>

app/views/athlets/show.html.erb
<br />
<br />

<div class="row">
<div class="col-md-6">

  <%= link_to 'Bearbeiten', edit_athlet_path(@athlet), :class => 'btn btn-default' %>
  <%= link_to 'Übersicht', athlets_path, :class => 'btn btn-default' %>
  <%= link_to 'Weiteren Athleten erfassen', new_athlet_path(:eventname => @athlet.eventname), :class => 'btn btn-default' %>


  <br />
  <br />

  <table class="table huge">
  <tr><th>Starter:</th>
  <td><%= @athlet.starter %></span></td></tr>

  <tr><th width="50%">Vorname:</th>
  <td><%= @athlet.firstname %></td></tr>

  <tr><th>Nachname:</th>
  <td><%= @athlet.surname %></td></tr>

  <tr><th>Geburtstag:</th>
  <td><%= @athlet.birthday %></td></tr>

  <tr><th>Geschlecht:</th>
  <td><%= @athlet.sex %></td></tr>

  <tr><th>Club:</th>
  <td><%= @athlet.club %></td></tr>

  <tr><th>Event:</th>
  <td><%= @athlet.eventname %></td></tr>

  <tr><th>Relay Team Size:</th>
  <td><%= @athlet.relaytmsize %></td></tr>

  <tr><th>Transponder Id:</th>
  <td><%= @athlet.transponderid %></td></tr>

  <tr><th>Startzeit:</th>
  <td><%= @athlet.starttime %></td></tr>

  <tr><th>Additionals:</th>
  <td><%= @athlet.additionals %></td></tr>

</table>

</div>
</div>

app/views/athlets/show_multiple.html.erb
<dl class="dl-horizontal">
  <dt>Club:</dt>
  <dd><%= @athlets.first.club %></dd>

  <dt>Event:</dt>
  <dd><%= @athlets.first.eventname %></dd>

  <dt>Relay Starter:</dt>
  <dd><%= @athlets.first.relaystarter %></dd>
</dl>

<% @athlets.each do |athlet| %>

  <dl class="dl-horizontal">
    <dt>Starter:</dt>
    <dd><%= athlet.starter %></dd>

    <dt>Firstname:</dt>
    <dd><%= athlet.firstname %></dd>

    <dt>Surname:</dt>
    <dd><%= athlet.surname %></dd>

    <dt>Birthday:</dt>
    <dd><%= athlet.birthday %></dd>

    <dt>Sex:</dt>
    <dd><%= athlet.sex %></dd>

    <dt>Relay Team Size:</dt>
    <dd><%= athlet.relaytmsize %></dd>

    <dt>Relay Team Member:</dt>
    <dd><%= athlet.relaytm %></dd>

    <dt>Transponder Id:</dt>
    <dd><%= athlet.transponderid %></dd>

    <dt>Startzeit:</dt>
    <dd><%= athlet.starttime %></dd>

    <dt>Additionals:</dt>
    <dd><%= athlet.additionals %></dd>
  </dl>
<% end %>

<%= link_to 'Bearbeiten', edit_multiple_athlets_path(:relaystarter => @athlets.first.relaystarter), :class => 'btn btn-default' %>
<%= link_to 'Übersicht', athlets_path, :class => 'btn btn-default' %>