config/routes.rb
Rails.application.routes.draw do
  resources :events

  resources :athlets do
    collection do
      get :autocomplete_firstname
      get :autocomplete_surname
      get :autocomplete_club
      post :import
      get :suggestions
      delete :destroy_all

      get :show_multiple
      get :new_multiple
      get :edit_multiple
      post :create_multiple
      put :update_multiple
      put :destroy_multiple
    end
  end

  resources :relays do
    collection do
      delete :destroy_all
    end
  end

  root 'static_pages#home'

  
  get 'datatable_i18n', to: 'datatables#datatable_i18n'
 
end

app/models/relay.rb
class Relay < Tableless
  #has_no_table
  has_many :athlets, :primary_key => :relaystarter, :foreign_key => :relaystarter, :class_name => RelayMember
  accepts_nested_attributes_for :athlets

  #attr_accessor :id
  attr_accessor :new_record

  column :club, :string
  column :eventname, :string
  column :relaystarter, :integer
  column :relaytmsize, :integer
  column :relaystarttime, :string


  validates :club, :presence => true, length: { minimum: 1 }
  validates :eventname, :presence => true
  validates :relaystarter, :presence => true

  after_initialize :set_defaults
  after_initialize :build_athlets

  #attr_accessible :club, :eventname, :relaystarter, :relaytm, :athlets_attributes
  #def id
  #  @id ||= 1
  #end
  
  def self.allowed_attributes
    ['club', 'eventname', 'relaystarter', 'relaytmsize']
  end

  def self.find(id)
    athlets = Athlet.where(:relaystarter => id)

    if athlets
      puts athlets.first.attributes
      Relay.new(athlets.first.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false}))
    else
      nil
    end
  end


  def self.all
    athlets = Athlet.where.not(:relaytmsize => 1).group(:relaystarter).all
    athlets.map{ |athlet| Relay.new(athlet.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false})) }
  end

  def self.event(name)
    athlets = Athlet.where(:eventname => name).group(:relaystarter).all
    #merged = athlet.attributes.slice(Relay.allowed_attributes).merge({:new_record => false})
    #athlets.map{ |athlet| Relay.new(merged) }
    athlets.map do |athlet|
      merged = athlet.attributes.slice(*Relay.allowed_attributes).merge({:new_record => false})
      Relay.new(merged)
    end
  end

  def to_param
    self.relaystarter
  end

  def set_defaults
    #self.relaytmsize ||= self.event.team_size
    self.relaytmsize ||= 4
  end

  def build_athlets
    (relaytmsize - athlets.size).times do
      self.athlets.build
    end if self.new_record?
  end

  def save
    if valid?
      # Maybe capture this in a transaction
      index = 1
      self.athlets.map do |athlet|
        athlet.assign_attributes(self.attributes.slice(*Relay.allowed_attributes))
        athlet.starter = (athlet.relaystarter * 10) + index
        athlet.relaytm = index
        if athlet.transponderid.blank?
          athlet.transponderid = athlet.starter;
        end
        if athlet.starttime.blank?
          if !self.relaystarttime.blank?
              athlet.starttime = self.relaystarttime
          end
        end
        athlet.save
        index = index + 1
      end
    end
  end

  def destroy
    self.athlets.map(&:destroy)
  end

  # def update(params)
  #   params
  #   debugger
  # end
end

app/controllers/relays_controller.rb
class RelaysController < ApplicationController
  before_action :set_relay, only: [:show, :edit, :update, :destroy]

  include ActionView::Helpers::TextHelper

  def index
    
    if params[:eventname]
      session[:eventRelay] = params[:eventname]
    end
    # @relays = Relay.all

    # respond_to do |format|
    #   format.html
    #   format.csv { send_data @relays.to_csv }
    #   format.xls { send_data @relays.to_xls(
    #     #:except => [:created_at, :updated_at]
    #     :columns => Relay::allowed_attributes,
    #     :headers => Relay::allowed_attributes
    #   ) }
    # end
  end


  def show
  end


  def new
    event = Event.where(:name => params[:eventname]).first
    @relay = Relay.new(:relaytmsize => event.team_size, :eventname => event.name)
    #session[:eventRelay] = params[:eventRelay]
    session[:eventRelay] = @relay.eventname
  end


  def edit
    #session[:eventRelay] = params[:eventRelay]
    session[:eventRelay] = @relay.eventname
  end


  def create
    @relay = Relay.new(relay_params)

    if @relay.save
      redirect_to relay_path(:id => @relay.relaystarter), notice: 'Relay was successfully created.'
    else
      render :new
    end
  end


  def update
    if @relay.update(relay_params)
      session[:eventRelay] = @relay.eventname
      redirect_to relay_path(:id => @relay.relaystarter), notice: 'Relay was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @relay.destroy
    session[:eventRelay] = @relay.eventname
    redirect_to relays_url, notice: 'Relay was successfully destroyed.'
  end


  def destroy_all
    @athlets = Athlet.where.not(:relaytmsize => 1)
    @athlets.destroy_all
    redirect_to root_url, notice: 'Relays were successfully destroyed.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relay
      @relay = Relay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relay_params
      params.require(:relay).permit(:club, :eventname, :relaytm, :relaystarter, :relaytmsize, :relaystarttime,
                                    :athlets_attributes => [:starter, :firstname, :surname, :birthday, :sex, :club, :eventname, :relaytm, :relaystarter, :relaytmsize, :id, :transponderid, :starttime, :additionals])
    end
end

app/views/relays/_athlet_fields.html.erb
<% athlet = f.object %>

<% if false %><!-- Errors -->
  <li>
    <%= hidden_field_tag "athlet_ids[]", athlet.id %>
    <%= athlet.surname %>
    <ul class="errors">
      <% athlet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </li>
<% end %>


<div class="col-md-6">
  <div class="panel panel-default athlet">
    <div class="panel-body">
      <fieldset>
        <legend>
          <%#= fa_icon "users" %>
          Athlet <%= athlet.relaytm %>
        </legend>
        <% if athlet.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(athlet.errors.count, "error") %> prohibited this athlet from being saved:</h2>
            <ul>
            <% athlet.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.input :firstname, :input_html => {
          :class => :firstname, :data => { :autocomplete => autocomplete_firstname_athlets_path } } %>
        <%= f.input :surname, :input_html => {
          :class => :surname, :data => { :autocomplete => autocomplete_surname_athlets_path } } %>
        <%#= f.input :birthday, :as => :integer, :input_html => { :class => :birthday, :value => athlet.birthday } %>
        <%= f.input :birthday, :as => :string, :input_html => { :class => :birthday, :value => athlet.birthday } %>
        <%# http://stackoverflow.com/questions/10767859/overriding-model-attribute-readers-does-not-affect-simple-form-input-fields %>
        <%#= f.input :sex %>

        <%= f.input :sex, collection: [:M, :W, :U], :input_html => { :class => :sex } %>

        <%= f.input :relaytmsize, :input_html => { :class => :relaytmsize }, :as => :hidden %>
        <%= f.input :transponderid, :input_html => { :class => :transponderid } %>
        <%= f.input :starttime, :input_html => { :class => :starttime } %>
        <%= f.input :additionals, :input_html => { :class => :additionals } %>

      </fieldset>
    </div>
  </div>
</div>

app/views/relays/_form.html.erb

<div class="row relay">
  <div class="col-xs-8">
    <%#= simple_form_for(@relay, :url => formurl, :method => formmethod, html: { class: 'form-horizontal' },%>
    <%= simple_form_for(@relay, html: { class: 'form-horizontal' },
  wrapper: :horizontal_form,
  wrapper_mappings: {
    check_boxes: :horizontal_radio_and_checkboxes,
    radio_buttons: :horizontal_radio_and_checkboxes,
    file: :horizontal_file_input,
    boolean: :horizontal_boolean
  }) do |f| %>
              <% if @relay.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@relay.errors.count, "error") %> prohibited this @relay from being saved:</h2>
                  <ul>
                  <% @relay.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-primary">
        <div class="panel-heading">Staffel</div>
        <div class="panel-body">
          <%= f.error_notification %>

          <div class="form-inputs">
            <%= f.input :club, :input_html => {
              :data => { :autocomplete => autocomplete_club_athlets_path } } %>
            <%#= f.input :event %>
            <%= f.input :eventname, :collection => Event.where(:team_size => @relay.relaytmsize).where(:active => true).order(:name => :asc), :label_method => :name, :value_method => :name , :include_blank => false %>
            <%= f.input :relaystarter %>
            <%= f.input :relaystarttime %>
            <%= f.input :relaytmsize, :as => :hidden %>

          </div>
        </div>
      </div>
    </div>

    <%= f.simple_fields_for :athlets do |athlet_form| %>
      <%= render 'athlet_fields', f:athlet_form %>
    <% end %>
  </div>
  <div class="actions">
    <%= submit_tag "Aktualisiern", :class => "btn btn-primary" %>
  </div>
<% end %>

  </div>
  <div class="col-xs-4">
    <div id="suggestionBar" class="affix-top" data-spy="affix" data-offset-top="160" data-offset-bottom="0">
      <div class="panel panel-primary athlet">
        <div class="panel-heading">
          <%= fa_icon 'refresh' %>
          Vorschläge
        </div>
      </div>
      <div id="suggestionBox"></div>
    </div>
  </div>
</div>

app/views/relays/edit.html.erb
<div class="page-header">
  <h1 id="navbar">Staffel bearbeiten</h1>
</div>
<%# pp @replay %>
<%#= render 'form', :formurl => "/relays/#{@relay.relaystarter}", :formmethod => :put %>
<%= render 'form' %>
<br>
<%= link_to 'Details', relay_path(:id => @relay.relaystarter), :class => 'btn btn-default' %>
<%= link_to 'Übersicht', relays_path, :class => 'btn btn-default' %>

app/views/relays/index.html.erb
<div class="page-header">
  <h1>Staffeln</h1>
</div>

<ul class="nav nav-tabs" role="tablist">
  <% events = Event.where.not(:team_size => 1).where(:active => true) %>
  <%# debugger %>
  <% session[:eventRelay] = Event.first.name if session[:eventRelay].nil? %>
  <% events.each do |event| %>
      <li class="<%= (event.name == session[:eventRelay]) ? 'active' : '' %>">
        <a href="#<%= event.name %>" role="tab" data-toggle="tab"><%= event.name %></a>
      </li>
  <% end %>
</ul>

<div class="tab-content">
  <% active = true %>
  <% Event.where.not(:team_size => 1).where(:active => true).each do |event| %>
      <div class="tab-pane <%= (event.name == session[:eventRelay]) ? 'active' : '' %>" id="<%= event.name %>">
        <% active = false %>
        <!-- <div class="section"> -->
        <div class="panel panel-primary">
          <div class="panel-heading">
            <div class="panel-title">
              <%= event.name %>
            </div>
          </div>
        </div>
        <%= link_to 'Neues Team', new_relay_path(:eventname => event.name), :class => 'btn btn-primary' %>
        <br />
        <br />
        <table class="table table-bordered table-striped datatable searchable">
          <thead>
          <tr>
            <th>Staffel-Startnummer</th>
            <th>Verein</th>
            <th>Veranstaltung</th>
            <th>Teamgröße</th>
            <th class="no-sort"></th>
          </tr>
          </thead>

          <tbody>
          <% Relay.event(event.name).each do |relay| %>
              <%# debugger %>
              <tr>
                <td><%= relay.relaystarter %></td>
                <td><%= link_to relay.club, relay_path(:id => relay.relaystarter) %></td>
                <td><%= relay.eventname %></td>
                <td><%= relay.relaytmsize %></td>
                <td>
                  <%= link_to edit_relay_path(:id => relay.relaystarter), :title => t("general.edit"), :data => {:toggle => "tooltip"} do %>
                      <%= tag :span, :class => "glyphicon glyphicon-edit" %>
                  <% end %>
                  <%= link_to relay_path(:id => relay.relaystarter), :title => t("general.destroy"), data: {confirm: t('general.are_you_sure'), :toggle => "tooltip"}, method: :delete do %>
                      <%= tag :span, :class => "glyphicon glyphicon-trash" %>
                  <% end %>
                </td>
              </tr>
          <% end %>
          </tbody>
        </table>
        <%= link_to 'Neues Team', new_relay_path(:eventname => event.name), :class => 'btn btn-primary' %>
      </div>
  <% end %>
</div>

app/views/relays/new.html.erb
<div class="page-header">
  <h1 id="navbar">Neue Staffel anmelden</h1>
</div>

<%#= render 'form',  :formurl => "/relays/new", :formmethod => :get %>
<%= render 'form' %>

<br />
<%= link_to 'Übersicht', relays_path, :class => 'btn btn-default' %>

app/views/relays/show.html.erb
<dl class="dl-horizontal">
  <dt>Verein (Staffelname):</dt>
  <dd><%= @relay.club %></dd>

  <dt>Veranstaltung:</dt>
  <dd><%= @relay.eventname %></dd>

  <dt>Staffel-Starternummer:</dt>
  <dd><%= @relay.relaystarter %></dd>

  <dt>Staffel-Teamgröße:</dt>
  <dd><%= @relay.relaytmsize %></dd>

  <dt>Startzeit:</dt>
  <dd><%= @relay.relaystarttime %></dd>
</dl>

<%= link_to 'Bearbeiten', edit_relay_path(:id => @relay.relaystarter), :class => 'btn btn-default' %>
<%= link_to 'Übersicht', relays_path, :class => 'btn btn-default' %>
<%= link_to 'Neues Team', new_relay_path(:eventname => @relay.eventname), :class => 'btn btn-default' %>

<br />
<br />

<table class="table table-bordered table-striped datatable searchable">
  <thead>
  <tr>
    <th>Starternummer</th>
    <th>Name</th>
    <th>Geburtsjahr</th>
    <th>Geschlecht</th>
    <th>Staffel-Teilnehmer</th>
    <th>Transp.-Id</th>
    <th>Startzeit</th>
    <th>Additionals</th>
  </tr>
  </thead>

  <tbody>
  <% @relay.athlets.each do |athlet| %>
      <tr>
        <td><%= athlet.starter %></td>
        <td><%= athlet.name %></td>
        <td><%= athlet.birthday %></td>
        <td><%= athlet.sex %></td>
        <td><%= athlet.relaytm %></td>
        <td><%= athlet.transponderid %></td>
        <td><%= athlet.starttime %></td>
        <td><%= athlet.additionals %></td>
      </tr>
  <% end %>
  </tbody>
</table>

